import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Title from "@/components/Navbar";
import { CardProvider } from "@/context/CardContext";
// import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className}  antialiased`}>
        <CardProvider>
          <div className="flex  min-h-screen text-center flex-col  ">
            <Title />
            <main className="flex-1  ">{children}</main>
            {/* <Footer /> */}
          </div>
        </CardProvider>
      </body>
    </html>
  );
}
